In [2]:
import pandas as pd

df = pd.read_csv('Studentperform.txt')

In [3]:
df.head()

,Student ID,Name,Gender,Math Marks,Science Marks,English Marks,Attendance,Final Grade
0,S001,Aarav,M,78.0,85.0,82,92.0,A
1,S002,Diya,F,88.0,91.0,87,95.0,A
2,S003,Rohan,M,45.0,52.0,49,60.0,C
3,S004,Anaya,F,92.0,95.0,94,98.0,A+
4,S005,Virat,M,15.0,22.0,18,40.0,F

In [4]:
df.tail()

,Student ID,Name,Gender,Math Marks,Science Marks,English Marks,Attendance,Final Grade
13,S014,Simran,F,95.0,97.0,96,99.0,A+
14,S015,Amit,M,150.0,140.0,145,110.0,A+
15,S016,Riya,F,64.0,59.0,62,-10.0,C
16,S017,Dev,M,83.0,78.0,80,92.0,B+
17,S018,Tanvi,F,NaN,88.0,91,94.0,A

In [5]:
df.isnull().sum()

Student ID       0
Name             0
Gender           0
Math Marks       1
Science Marks    1
English Marks    0
Attendance       1
Final Grade      0
dtype: int64

In [11]:
df = df.fillna(50)

In [12]:
df.isnull().sum()

Student ID       0
Name             0
Gender           0
Math Marks       0
Science Marks    0
English Marks    0
Attendance       0
Final Grade      0
dtype: int64

In [13]:
df.dtypes

Student ID        object
Name              object
Gender            object
Math Marks       float64
Science Marks    float64
English Marks      int64
Attendance       float64
Final Grade       object
dtype: object

In [14]:
m = df['Math Marks'].mean()
print("Math Mean = ",m)
df['Math Marks'] = df['Math Marks'].fillna(m)

Math Mean =  71.05555555555556

In [15]:
import numpy as np
df['Attendance'] = np.log(df['Attendance'])

C:\Users\Arshad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [16]:
df.head()

,Student ID,Name,Gender,Math Marks,Science Marks,English Marks,Attendance,Final Grade
0,S001,Aarav,M,78.0,85.0,82,4.521789,A
1,S002,Diya,F,88.0,91.0,87,4.553877,A
2,S003,Rohan,M,45.0,52.0,49,4.094345,C
3,S004,Anaya,F,92.0,95.0,94,4.584967,A+
4,S005,Virat,M,15.0,22.0,18,3.688879,F

In [20]:
Q1 = df['Math Marks'].quantile(0.25)
Q3 = df['Math Marks'].quantile(0.75)

d = Q3-Q1
lower = Q1 - 1.5 * d
upper = Q3 + 1.5*d

df['Math Marks'] = np.where(df['Math Marks'] > upper ,m,df['Math Marks'])
df['Math Marks'] = np.where(df['Math Marks'] < lower ,m,df['Math Marks'])

In [23]:
#outliners in math

for m in df['Math Marks']:
    if m<lower or m>upper:
        print(m)

In [28]:
#outliners in science using IQR


Q1 = df['Science Marks'].quantile(0.25)
Q3 = df['Science Marks'].quantile(0.75)

d = Q3-Q1
lower = Q1 - 1.5 * d
upper = Q3 + 1.5*d

for m in df['Science Marks']:
    if m <lower or m>upper:
        print(m)